cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: dbd-project
    credentials:
      access-key: ${S3-ACCESS-KEY}
      secret-key: ${S3-SECRET-KEY}
      stack:
        auto: false