name: dbd-backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  S3_BUCKET_NAME: dbd-project

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: (Release) Get current date
      id: date
      run: echo "::set-output name=date::$(date + '%Y/%m/%d')"
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: ./gradlew clean build
      shell: bash

     # 디렉토리 생성
    - name: Make Directory
      run: mkdir -p deploy
        
    # Jar 파일 복사
    - name: Copy Jar
      run: cp ./build/libs/*.jar ./deploy

    # appspec.yml 파일 복사
    - name: Copy appspec.yml
      run: cp appspec.yml ./deploy

    - name: Make zip file
      run: zip -r ./dbdBackend.zip ./deploy
      shell: bash

    # script files 복사
    - name: Copy script
      run: cp ./scripts/*.sh ./deploy

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./dbdBackend.zip s3://$S3_BUCKET_NAME/

    # Deploy
    - name: Deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      run: |
        aws deploy create-deployment --application-name dbd-project --deployment-config-name --ignore-application-stop-failures  CodeDeployDefault.AllAtOnce --deployment-group-name dbd-group --s3-location bucket=dbd-project,bundleType=zip,key=dbdBackend.zip \
        --region ap-northeast-2
        
